name: main

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.12"
            toxenv: "py312"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
      - name: Install tox
        run: pip install tox
      - name: Run tox test env
        run: tox -r -e ${{ matrix.python.toxenv }}
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-file
          path: coverage.xml

  codacy-coverage-reporter:
    needs: test
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: coverage-file
          path: coverage.xml
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
  
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install tox
        run: pip install tox
      - name: Rox tox env to build docs
        run: tox -r -e docs
